### ISSUE TITLE
 NameError: name 'force_reload' is not defined

### ISSUE THREAD

**Issue by hamza-maqsood** [neutron-sync/django-easy-logging#1]
backend-1  |     load_loguru(globals())
backend-1  |   File "/usr/local/lib/python3.9/site-packages/dj_easy_log.py", line 67, in load_loguru
backend-1  |     if not LOGGING_LOADED or force_reload:
backend-1  | NameError: name 'force_reload' is not defined

---------------

getting this error when trying to run the django app

using these versions
Django~=4.2.3
django-easy-logging==0.60
loguru==0.7.0

**Comment by chrismaille** [comment]
The workaround I use:

```python
# settings.py
from dj_easy_log import load_loguru

RUNNING_TESTS = "pytest" in sys.modules or "test" in sys.argv

if not RUNNING_TESTS:
    load_loguru(globals())

```

**Comment by pizzapanther** [comment]
OK I must have missed the email notification for the original issue but I got one when @chrismaille responded. So it's fixed now @hamza-maqsood. Version 0.7.0 published https://pypi.org/project/django-easy-logging/
